services:
  djangoapp:
    container_name: PokeAPI_Django
    image: pokeapi-django:latest
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./PokeAPI_Django:/PokeAPI_Django
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      - ./Doc:/Doc
      - ./Doc/output:/PokeAPI_Django/Doc/output
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
  plantuml:
    container_name: plantuml
    image: plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"
  docs:
    build:
      context: .
    container_name: docs_generator
    volumes:
      - ./Doc:/PokeAPI_Django/Doc
    command: ["/scripts/generate_docs.sh"]